version: 2.1

orbs:
  newspack: newspack/newspack@1.4.3

commands:
  checkout_code:
    steps:
      - checkout
      - attach_workspace:
          at: ~/

jobs:
  # Release job. Required over newspack/release because of the need to version bump additional files.
  release:
    docker:
      - image: cimg/node:16.11.1
    steps:
      - checkout_code
      - run:
          name: Release new version
          command: npm run release
      - persist_to_workspace:
          root: ~/
          paths:
            - project

workflows:
  version: 2
  all:
    jobs:
      - newspack/build
      - newspack/lint-js-scss:
          requires:
            - newspack/build
      - newspack/build-distributable:
          requires:
            - newspack/build
          archive-name: 'newspack-block-theme'
          filters:
            branches:
              only:
                - master
      - release:
          requires:
            - newspack/build
          filters:
            branches:
              only:
                - release
                - alpha
                - /^hotfix\/.*/
      - newspack/post-release:
          requires:
            - newspack/release
          filters:
            branches:
              only:
                - release
  php:
    jobs:
      - newspack/lint-php
