version: 2.1

orbs:
  newspack: newspack/newspack@1.4.3

jobs:
  # Release job. Required over newspack/release because of the need to version bump additional files.
  release:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout_with_workspace
      - set_node_version
      - run:
          name: Install rsync
          command: sudo apt-get update && sudo apt-get install rsync
      - run:
          name: Install PHP packages
          command: composer install --no-dev --no-scripts
      - run:
          name: Release new version
          command: npm run release
      - persist_to_workspace:
          root: ~/
          paths:
            - project

workflows:
  version: 2
  all:
    jobs:
      - newspack/build
      - newspack/lint-js-scss:
          requires:
            - newspack/build
      - newspack/build-distributable:
          requires:
            - newspack/build
          archive-name: 'newspack-block-theme'
          filters:
            branches:
              only:
                - master
      - release:
          requires:
            - newspack/build
          filters:
            branches:
              only:
                - release
                - alpha
                - /^hotfix\/.*/
      - newspack/post-release:
          requires:
            - release
          filters:
            branches:
              only:
                - release
  php:
    jobs:
      - newspack/lint-php
